#Requires -Version 5.1
<#
.SYNOPSIS
    USB & StreamDeck Health Checker — runs at startup, auto-fixes common issues,
    and appends a timestamped report to a rolling log file.

.DESCRIPTION
    1. Scans all USB/HID devices via WMI (fast, no PnpDevice hang)
    2. Detects StreamDeck (Elgato) — found / missing / error
    3. Attempts auto-remediation: restart driver, kill/restart StreamDeck software
    4. Calculates health metrics and writes a report
    5. Appends the report to a persistent log for trend analysis

.NOTES
    Register as a Scheduled Task (see bottom of file).
    Location: C:\projects\workstation\6_Symbols\startup\Check-USBDevices.ps1
    Author  : Erdem  |  Auto-generated by GitHub Copilot
#>

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────
$ReportDir  = "$env:APPDATA\USBHealthChecker"
$LogFile    = "$ReportDir\usb_health_log.txt"
$JsonLog    = "$ReportDir\usb_health_log.json"
$MaxLogDays = 30   # rolling window — entries older than this are pruned

# Known StreamDeck / Elgato USB vendor/product strings
$StreamDeckPatterns = @('elgato', 'stream deck', 'streamdeck', 'vid_0fd9')

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────
function Ensure-Dir {
    if (-not (Test-Path $ReportDir)) {
        New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
    }
}

function Write-Section($title) {
    $line = "─" * 64
    Write-Host ""
    Write-Host $line -ForegroundColor DarkGray
    Write-Host "  $title" -ForegroundColor Cyan
    Write-Host $line -ForegroundColor DarkGray
}

function Write-Banner {
    Clear-Host
    Write-Host ""
    Write-Host "  ╔══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "  ║   USB & STREAMDECK HEALTH CHECKER   by Erdem            ║" -ForegroundColor Cyan
    Write-Host "  ║   $(Get-Date -Format 'yyyy-MM-dd  HH:mm:ss')                            ║" -ForegroundColor DarkCyan
    Write-Host "  ╚══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

# Returns all USB + HID devices via CIM (fast, no implicit remoting)
function Get-AllUSBDevices {
    $usb = Get-CimInstance -ClassName Win32_PnPEntity -Filter "PNPClass='USB' OR PNPClass='HIDClass' OR PNPClass='USBDevice'" -ErrorAction SilentlyContinue
    if (-not $usb) {
        $usb = Get-CimInstance -ClassName Win32_PnPEntity | Where-Object {
            $_.DeviceID -match '^USB\\' -or $_.DeviceID -match '^HID\\'
        }
    }
    return $usb
}

# Returns devices with non-zero error codes (WQL-filtered, no full scan)
function Get-ProblemDevices {
    Get-CimInstance -ClassName Win32_PnPEntity -Filter "ConfigManagerErrorCode <> 0" -ErrorAction SilentlyContinue
}

# Matches a device against StreamDeck patterns
function Test-IsStreamDeck($device) {
    foreach ($pat in $StreamDeckPatterns) {
        if ($device.Name -match $pat -or $device.DeviceID -match $pat -or
            $device.Description -match $pat -or $device.Manufacturer -match $pat) {
            return $true
        }
    }
    return $false
}

# Attempt to restart the StreamDeck process
function Restart-StreamDeckSoftware {
    $sdProcess = Get-Process | Where-Object { $_.ProcessName -match 'streamdeck|elgato' } -ErrorAction SilentlyContinue
    if ($sdProcess) {
        Write-Host "  ⚡ Restarting StreamDeck software..." -ForegroundColor Yellow
        $exePath = $sdProcess | Select-Object -First 1 | ForEach-Object { $_.Path }
        $sdProcess | ForEach-Object {
            try { $_ | Stop-Process -Force -ErrorAction SilentlyContinue } catch {}
        }
        Start-Sleep -Seconds 2
        if ($exePath -and (Test-Path $exePath)) {
            Start-Process $exePath
            Write-Host "  ✓ StreamDeck relaunched: $exePath" -ForegroundColor Green
            return "Restarted: $exePath"
        } else {
            Write-Host "  ⚠ Could not find StreamDeck exe to relaunch." -ForegroundColor DarkYellow
            return "Stopped (exe not found)"
        }
    } else {
        # Try common install paths
        $commonPaths = @(
            "$env:ProgramFiles\Elgato\StreamDeck\StreamDeck.exe",
            "${env:ProgramFiles(x86)}\Elgato\StreamDeck\StreamDeck.exe",
            "$env:LOCALAPPDATA\Programs\Elgato\StreamDeck\StreamDeck.exe"
        )
        foreach ($p in $commonPaths) {
            if (Test-Path $p) {
                Start-Process $p
                Write-Host "  ✓ StreamDeck launched from: $p" -ForegroundColor Green
                return "Launched: $p"
            }
        }
        Write-Host "  ✗ StreamDeck software not found in common locations." -ForegroundColor Red
        return "Not found"
    }
}

# Disable + re-enable a USB device via devcon or pnputil workaround
function Reset-USBDevice($deviceId) {
    # We use pnputil to scan for device changes (safe, no devcon needed)
    try {
        $null = pnputil /scan-devices 2>&1
        Write-Host "  ✓ pnputil /scan-devices triggered (USB re-enumeration)" -ForegroundColor Green
        return "pnputil scan triggered"
    } catch {
        return "pnputil failed: $_"
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# FORMULAS / METRICS
# ─────────────────────────────────────────────────────────────────────────────
<#
  HEALTH SCORE FORMULA
  ─────────────────────
  HealthScore (0-100) = 100
      - (ProblemDeviceCount  × 10)   [each broken device  = -10 pts]
      - (StreamDeckMissing   × 30)   [StreamDeck not found = -30 pts]
      - (USBErrorCount       × 5 )   [each USB error code  =  -5 pts]

  USB DEVICE RATIO
  ────────────────
  HealthRatio = WorkingDevices / TotalUSBDevices  (percentage)

  STABILITY INDEX
  ────────────────
  Over the rolling log window:
  StabilityIndex = (RunsWithScore100 / TotalRuns) × 100
#>
function Compute-HealthScore($problemCount, $sdMissing, $usbErrorCount) {
    $score = 100
    $score -= ($problemCount  * 10)
    $score -= ($sdMissing     * 30)
    $score -= ($usbErrorCount *  5)
    return [Math]::Max(0, $score)
}

function Compute-HealthRatio($working, $total) {
    if ($total -eq 0) { return 0 }
    return [Math]::Round(($working / $total) * 100, 1)
}

function Compute-StabilityIndex($jsonLogPath) {
    if (-not (Test-Path $jsonLogPath)) { return "N/A (no history)" }
    try {
        $entries = Get-Content $jsonLogPath -Raw | ConvertFrom-Json
        $cutoff  = (Get-Date).AddDays(-$MaxLogDays)
        $recent  = @($entries | Where-Object { [datetime]$_.Timestamp -gt $cutoff })
        if ($recent.Count -eq 0) { return "N/A (no recent runs)" }
        $perfect = @($recent | Where-Object { $_.HealthScore -eq 100 }).Count
        $index   = [Math]::Round(($perfect / $recent.Count) * 100, 1)
        return "$index% over last $($recent.Count) runs (window: ${MaxLogDays}d)"
    } catch {
        return "N/A (parse error)"
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────
Ensure-Dir
Write-Banner

$runTime    = Get-Date
$actionsTaken = @()
$findings   = @()

# ── 1. SCAN USB DEVICES ───────────────────────────────────────────────────────
Write-Section "Scanning USB & HID Devices"
$allUSB = Get-AllUSBDevices
$totalUSB   = $allUSB.Count
$workingUSB = @($allUSB | Where-Object { $_.ConfigManagerErrorCode -eq 0 }).Count
$usbErrors  = @($allUSB | Where-Object { $_.ConfigManagerErrorCode -ne 0 -and $_.ConfigManagerErrorCode -ne $null })

Write-Host ("  Total USB/HID devices  : {0}" -f $totalUSB) -ForegroundColor White
Write-Host ("  Working (ErrorCode=0)  : {0}" -f $workingUSB) -ForegroundColor Green
Write-Host ("  Error   (ErrorCode≠0)  : {0}" -f $usbErrors.Count) -ForegroundColor $(if ($usbErrors.Count -gt 0) { "Red" } else { "Green" })
Write-Host ("  Health Ratio Formula   : {0} / {1} × 100 = {2}%" -f $workingUSB, $totalUSB, (Compute-HealthRatio $workingUSB $totalUSB)) -ForegroundColor DarkCyan

if ($usbErrors.Count -gt 0) {
    Write-Host ""
    Write-Host "  ⚠ Devices with errors:" -ForegroundColor Red
    foreach ($d in $usbErrors) {
        $msg = "    • [{0}] {1} (ErrorCode: {2})" -f $d.PNPClass, $d.Name, $d.ConfigManagerErrorCode
        Write-Host $msg -ForegroundColor Red
        $findings += $msg.Trim()
    }
}

# ── 2. DETECT STREAMDECK ──────────────────────────────────────────────────────
Write-Section "StreamDeck Detection"
$sdDevices = @($allUSB | Where-Object { Test-IsStreamDeck $_ })
$sdProcess = Get-Process | Where-Object { $_.ProcessName -match 'streamdeck|elgato' } -ErrorAction SilentlyContinue
$sdSoftwareRunning = $sdProcess.Count -gt 0
$sdMissing = 0

if ($sdDevices.Count -gt 0) {
    Write-Host "  ✓ StreamDeck hardware FOUND:" -ForegroundColor Green
    foreach ($sd in $sdDevices) {
        Write-Host ("    • {0}  [{1}]  Status: {2}" -f $sd.Name, $sd.DeviceID, $sd.Status) -ForegroundColor Green
    }
    $findings += "StreamDeck hardware detected: $($sdDevices.Count) device(s)"
} else {
    Write-Host "  ✗ StreamDeck hardware NOT detected in USB/HID scan." -ForegroundColor Red
    $sdMissing = 1
    $findings += "StreamDeck hardware NOT found"

    # Auto-fix attempt 1: pnputil rescan
    Write-Host ""
    Write-Host "  → Attempting USB re-enumeration via pnputil..." -ForegroundColor Yellow
    $r1 = Reset-USBDevice ""
    $actionsTaken += "USB re-enumeration: $r1"
    Start-Sleep -Seconds 3

    # Re-check after rescan
    $allUSB2  = Get-AllUSBDevices
    $sdCheck2 = @($allUSB2 | Where-Object { Test-IsStreamDeck $_ })
    if ($sdCheck2.Count -gt 0) {
        Write-Host "  ✓ StreamDeck found after re-enumeration!" -ForegroundColor Green
        $sdMissing = 0
        $findings += "StreamDeck found after pnputil re-enumeration"
        $actionsTaken += "StreamDeck recovered by USB re-enumeration"
    } else {
        Write-Host "  ✗ StreamDeck still not found after re-enumeration." -ForegroundColor Red
        $findings += "StreamDeck still absent after re-enumeration"
    }
}

Write-Host ""
Write-Host ("  StreamDeck software running: {0}" -f $(if ($sdSoftwareRunning) { "YES ✓" } else { "NO ✗" })) `
    -ForegroundColor $(if ($sdSoftwareRunning) { "Green" } else { "Red" })

# Auto-fix attempt 2: restart software if hardware present but software dead
if ($sdMissing -eq 0 -and -not $sdSoftwareRunning) {
    Write-Host ""
    Write-Host "  → Hardware OK but software not running. Launching StreamDeck..." -ForegroundColor Yellow
    $r2 = Restart-StreamDeckSoftware
    $actionsTaken += "StreamDeck software: $r2"
} elseif ($sdMissing -eq 0 -and $sdSoftwareRunning) {
    Write-Host "  → Software already running — no action needed." -ForegroundColor DarkGray
} elseif ($sdMissing -eq 1) {
    # Hardware not found — restart software in case it recovers on reconnect
    $r3 = Restart-StreamDeckSoftware
    $actionsTaken += "StreamDeck software restart attempt: $r3"
}

# ── 3. PROBLEM DEVICES SUMMARY ────────────────────────────────────────────────
Write-Section "All Problem Devices (System-wide)"
$allProblems = Get-ProblemDevices
if ($allProblems.Count -eq 0) {
    Write-Host "  ✓ No problem devices found." -ForegroundColor Green
} else {
    Write-Host ("  ⚠ {0} device(s) with errors:" -f $allProblems.Count) -ForegroundColor Red
    foreach ($d in ($allProblems | Select-Object -First 20)) {
        Write-Host ("    • [{0}] {1} — ErrorCode {2}" -f $d.PNPClass, $d.Name, $d.ConfigManagerErrorCode) -ForegroundColor Red
    }
}

# ── 4. HEALTH SCORE ───────────────────────────────────────────────────────────
Write-Section "Health Score Calculation"
$healthScore = Compute-HealthScore $allProblems.Count $sdMissing $usbErrors.Count
$healthRatio = Compute-HealthRatio $workingUSB $totalUSB
$stability   = Compute-StabilityIndex $JsonLog

$scoreColor = if ($healthScore -ge 80) { "Green" } elseif ($healthScore -ge 50) { "Yellow" } else { "Red" }

Write-Host ""
Write-Host "  FORMULA:" -ForegroundColor DarkCyan
Write-Host ("  HealthScore = 100 - (ProblemDevices×10) - (SDMissing×30) - (USBErrors×5)") -ForegroundColor DarkGray
Write-Host ("             = 100 - ({0}×10) - ({1}×30) - ({2}×5)" -f $allProblems.Count, $sdMissing, $usbErrors.Count) -ForegroundColor DarkGray
Write-Host ("             = {0}" -f $healthScore) -ForegroundColor $scoreColor
Write-Host ""
Write-Host ("  USB Health Ratio : {0}%  ({1}/{2} devices OK)" -f $healthRatio, $workingUSB, $totalUSB) -ForegroundColor White
Write-Host ("  Health Score     : {0}/100" -f $healthScore) -ForegroundColor $scoreColor
Write-Host ("  Stability Index  : {0}" -f $stability) -ForegroundColor DarkCyan
Write-Host ("  Actions Taken    : {0}" -f $(if ($actionsTaken.Count -eq 0) { "None" } else { $actionsTaken.Count })) -ForegroundColor White

# ── 5. WRITE REPORT ───────────────────────────────────────────────────────────
Write-Section "Writing Report"

$reportEntry = [PSCustomObject]@{
    Timestamp          = $runTime.ToString("yyyy-MM-dd HH:mm:ss")
    TotalUSBDevices    = $totalUSB
    WorkingUSBDevices  = $workingUSB
    USBErrorDevices    = $usbErrors.Count
    ProblemDeviceCount = $allProblems.Count
    StreamDeckFound    = ($sdMissing -eq 0)
    StreamDeckSoftware = $sdSoftwareRunning
    HealthScore        = $healthScore
    HealthRatio        = $healthRatio
    ActionsTaken       = ($actionsTaken -join " | ")
    Findings           = ($findings -join " | ")
}

# Append to human-readable text log
$textReport = @"

================================================================================
USB & STREAMDECK HEALTH REPORT
Timestamp   : $($reportEntry.Timestamp)
================================================================================
DEVICE SUMMARY
  Total USB/HID Devices   : $($reportEntry.TotalUSBDevices)
  Working Devices         : $($reportEntry.WorkingUSBDevices)
  Error Devices           : $($reportEntry.USBErrorDevices)
  All Problem Devices     : $($reportEntry.ProblemDeviceCount)

STREAMDECK STATUS
  Hardware Found          : $($reportEntry.StreamDeckFound)
  Software Running        : $($reportEntry.StreamDeckSoftware)

FORMULAS & METRICS
  HealthScore Formula     : 100 - (ProblemDevices × 10) - (SDMissing × 30) - (USBErrors × 5)
  HealthScore             : $($reportEntry.HealthScore) / 100
  USB Health Ratio        : $($reportEntry.HealthRatio)%  (Working / Total × 100)
  Stability Index         : $stability

ACTIONS TAKEN
  $(if ($actionsTaken.Count -eq 0) { "None" } else { $actionsTaken -join "`n  " })

FINDINGS
  $(if ($findings.Count -eq 0) { "None" } else { $findings -join "`n  " })
================================================================================
"@

Add-Content -Path $LogFile -Value $textReport -Encoding UTF8

# Append to JSON log (rolling)
$jsonHistory = @()
if (Test-Path $JsonLog) {
    try {
        $raw = Get-Content $JsonLog -Raw | ConvertFrom-Json
        $jsonHistory = @($raw)
    } catch { $jsonHistory = @() }
}
$cutoff     = (Get-Date).AddDays(-$MaxLogDays)
$jsonHistory = @($jsonHistory | Where-Object { [datetime]$_.Timestamp -gt $cutoff })
$jsonHistory += $reportEntry
ConvertTo-Json -InputObject $jsonHistory -Depth 5 | Set-Content $JsonLog -Encoding UTF8

Write-Host ("  ✓ Text log   : {0}" -f $LogFile) -ForegroundColor Green
Write-Host ("  ✓ JSON log   : {0}" -f $JsonLog) -ForegroundColor Green
Write-Host ""
Write-Host "  Done. Window closes in 8 seconds." -ForegroundColor DarkGray
Start-Sleep -Seconds 8


# ─────────────────────────────────────────────────────────────────────────────
# REGISTER AS STARTUP TASK  (run this block ONCE in an elevated PowerShell)
# ─────────────────────────────────────────────────────────────────────────────
<#
$ScriptPath = "C:\projects\workstation\6_Symbols\startup\Check-USBDevices.ps1"

$Action  = New-ScheduledTaskAction `
    -Execute  "pwsh.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$ScriptPath`""

$Trigger  = New-ScheduledTaskTrigger -AtLogOn

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 3)

Register-ScheduledTask `
    -TaskName   "USBStreamDeckHealthCheck" `
    -Action     $Action `
    -Trigger    $Trigger `
    -Settings   $Settings `
    -RunLevel   Highest `
    -Description "USB & StreamDeck health checker — runs at every login" `
    -Force
#>
