
$list = New-Object Collections.Generic.List[String]
$list.Add("audacity")
$list.Add("git.install")
$list.Add("git")
$list.Add("Firefox")
$list.Add("Everything")
$list.Add("dotnetfx")
$list.Add("docker-desktop")
$list.Add("discord")
$list.Add("curl")
$list.Add("chocolatey-windowsupdate.extension")
$list.Add("chocolatey-visualstudio.extension")
$list.Add("chocolatey-dotnetfx.extension")
$list.Add("chocolatey-dotnetfx.extension")
$list.Add("chocolatey-core.extension")
$list.Add("chocolatey")
$list.Add("ccleaner")
$list.Add("beyondcompare")
$list.Add("azure-cli")
$list.Add("awscli")
$list.Add("autohotkey.install")
$list.Add("autohotkey")
$list.Add("adobereader")
$list.Add("7zip.install")
$list.Add("microsoft-teams")
$list.Add("obs-studio")
$list.Add("notepadplusplus.install")
$list.Add("nomachine")
$list.Add("nodejs.install")
$list.Add("nodejs")
$list.Add("logitech-options")
$list.Add("lightshot.install")
$list.Add("jre8")
$list.Add("jdk8")
$list.Add("javaruntime")
$list.Add("GoogleChrome")
$list.Add("obs-studio.install")
$list.Add("greenshot")
$list.Add("slack")
$list.Add("skype")
$list.Add("python3")
$list.Add("python")
$list.Add("procexp")
$list.Add("PowerShell")
$list.Add("putty.install")
$list.Add("postman")
$list.Add("paint.net")
$list.Add("vscode")
$list.Add("vscode.install")
$list.Add("wox")
$list.Add("vlc")
$list.Add("visualstudio2019enterprise")
$list.Add("visualstudio-installer")
$list.Add("virtualbox")
$list.Add("vim")
$list.Add("vcredist2017")
$list.Add("vcredist2015")
$list.Add("vcredist140")
$list.Add("telegram.install")
$list.Add("telegram")
$list.Add("streamlabs-obs")
$list.Add("streamdeck")
$list.Add("steam-client")
$list.Add("sql-server-management-studio")
$list.Add("sourcetree")
$list.Add("audacity")

todo add a loop here
choco install  -y



choco list --localonly
todo verify install count
